# Version 0.0.1
FROM frolvlad/alpine-oraclejdk8
MAINTAINER WangJun 1500690060@qq.com
RUN mkdir -p /root/syswin/roc
WORKDIR /root/syswin/roc
ADD roc-gateway.jar /root/syswin/roc
CMD ["java", "-version"]
EXPOSE 35002